import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Business Site</title>
        <meta name="description" content="Generated by Codex" />
      </Head>
      <main>
        <h1>Welcome to Business Site</h1>
      </main>
    </div>
  );
}
